language: objective-c
cache: cocoapods
xcode_workspace: IntentKitDemo.xcworkspace
xcode_scheme: IntentKitDemo
xcode_sdk: iphonesimulator

before_install:
  - gem install cocoapods slather activesupport -N

after_success: slather